### PR TITLE
Organised Sticker directory

### PR DESCRIPTION
**Pull request by lauragift21**
I took the stab in organizing the stickers folder. I hope it looks better now.

### CODE REVIEW

**Comment by vmitchell85** [comment]
@lauragift21 I'm confused by the `zip files` directory... they all look like `.sketch` files to me.

**Comment by lauragift21** [comment]
Yes sorry about that they are also sketch files but zipped.

**Comment by wesbos** [comment]
thank you! Sorry this is so delayed

**Comment by lauragift21** [comment]
It's my pleasure.Congrats on the launch of your CSS Grid course.

**Pull request merged**
